import { z } from "zod";

export const ownerSchema = z.object({
  ownerName: z.string().min(1, "Owner name is required"),
  fatherHusbandName: z.string().min(1, "Father/Husband name is required"),
  mobileNumber: z.string().min(10, "Mobile number must be at least 10 digits"),
  ownershipShare: z.string().min(1, "Ownership share is required (e.g. 100%)"),
  address: z.string().min(1, "Address is required"),
});

export const valuationDetailsRowSchema = z.object({
  particularOfItem: z.string().min(1, "Item particular name is required"),
  plinthArea: z.number().nonnegative("Plinth area must be non-negative"),
  remainingAge: z.number().nonnegative("Age must be non-negative"),
  depreciationPct: z.number().min(0).max(100, "Depreciation percentage must be between 0 and 100"),
  replacementRate: z.number().nonnegative("Replacement rate must be non-negative"),
});

export const valuationFormSchema = z.object({
  // Step 1: Bank Details & Documents
  bankName: z.string(),
  branchName: z.string().min(1, "Branch name is required"),
  purposeOfValuation: z.string(),
  inspectionDate: z.string().min(1, "Inspection date is required"),
  valuationDate: z.string().min(1, "Valuation date is required"),
  perusalDocuments: z.string(),

  // Step 2: Owner Details
  owners: z.array(ownerSchema).min(1, "At least one owner is required"),

  // Step 3: Property Details
  propertyType: z.string(),
  ownershipType: z.string(),
  mortgageStatus: z.string(),
  plotNumber: z.string().min(1, "Plot number is required"),
  surveyNumber: z.string(),
  doorNumber: z.string(),
  village: z.string().min(1, "Village/City is required"),
  taluka: z.string().min(1, "Taluka is required"),
  district: z.string().min(1, "District is required"),
  state: z.string(),
  pincode: z.string().optional(),
  postalAddress: z.string().min(1, "Postal address is required"),
  areaClassification: z.string(),
  areaType: z.string(),
  municipalityType: z.string(),
  propertyDescription: z.string(),
  govtEnactments: z.string(),
  agriculturalConversion: z.string(),

  // Step 4: Site Details (Boundaries & Dimensions)
  boundaryNorthDeed: z.string(),
  boundaryNorthDeed2: z.string(),
  boundaryNorthSite: z.string(),
  boundarySouthDeed: z.string(),
  boundarySouthDeed2: z.string(),
  boundarySouthSite: z.string(),
  boundaryEastDeed: z.string(),
  boundaryEastDeed2: z.string(),
  boundaryEastSite: z.string(),
  boundaryWestDeed: z.string(),
  boundaryWestDeed2: z.string(),
  boundaryWestSite: z.string(),

  dimensionNorthDeed: z.string(),
  dimensionNorthDeed2: z.string(),
  dimensionNorthSite: z.string(),
  dimensionSouthDeed: z.string(),
  dimensionSouthDeed2: z.string(),
  dimensionSouthSite: z.string(),
  dimensionEastDeed: z.string(),
  dimensionEastDeed2: z.string(),
  dimensionEastSite: z.string(),
  dimensionWestDeed: z.string(),
  dimensionWestDeed2: z.string(),
  dimensionWestSite: z.string(),

  plotArea: z.number().positive("Plot area must be positive"),
  coveredArea: z.number().nonnegative("Covered area must be zero or positive"),
  numberOfFloors: z.number().int().positive(),
  latitude: z.string(),
  longitude: z.string(),
  gmapsUrl: z.string(),
  extentSite: z.string(),
  extentValuation: z.string(),
  occupancyDetails: z.string(),

  // Step 5: Site Characteristics (20 Items)
  charLocality: z.string(),
  charDevelopment: z.string(),
  charFlooding: z.string(),
  charCivicAmenities: z.string(),
  charLandLevel: z.string(),
  charLandShape: z.string(),
  charTypeUse: z.string(),
  charUsageRestriction: z.string(),
  charTownPlanning: z.string(),
  charCornerPlot: z.string(),
  charRoadFacilities: z.string(),
  charRoadType: z.string(),
  charRoadWidth: z.string(),
  charLandLocked: z.string(),
  charWaterPotential: z.string(),
  charSewerage: z.string(),
  charPowerSupply: z.string(),
  charAdvantages: z.string(),
  charDisadvantages: z.string(),
  charSpecialRemarks: z.string(),

  // Step 6: Building Material & Structural Specs
  buildingType: z.string(),
  constructionType: z.string(),
  yearOfConstruction: z.string(),
  plinthArea: z.string(),
  conditionExterior: z.string(),
  conditionInterior: z.string(),
  layoutApprovalDateValidity: z.string(),
  layoutApprovalAuthority: z.string(),
  layoutApprovalGenuineness: z.string(),
  layoutApprovalComments: z.string(),

  specFoundationGround: z.string(),
  specFoundationOther: z.string(),
  specBasementGround: z.string(),
  specBasementOther: z.string(),
  specSuperstructureGround: z.string(),
  specSuperstructureOther: z.string(),
  specJoineryGround: z.string(),
  specJoineryOther: z.string(),
  specRccGround: z.string(),
  specRccOther: z.string(),
  specPlasteringGround: z.string(),
  specPlasteringOther: z.string(),
  specFlooringGround: z.string(),
  specFlooringOther: z.string(),
  specSpecialFinishGround: z.string(),
  specSpecialFinishOther: z.string(),
  specRoofingGround: z.string(),
  specRoofingOther: z.string(),

  compoundHeight: z.string(),
  compoundLength: z.string(),
  compoundType: z.string(),

  electricalWiring: z.string(),
  electricalFitting: z.string(),
  electricalLightPoints: z.string(),
  electricalFanPoints: z.string(),
  electricalPlugs: z.string(),
  electricalOther: z.string(),

  plumbingWaterClosets: z.string(),
  plumbingWashBasins: z.string(),
  plumbingUrinals: z.string(),
  plumbingBathTubs: z.string(),
  plumbingWaterMeter: z.string(),
  plumbingOther: z.string(),

  // Step 7: Valuation Math & Tables
  marketRate: z.number().positive("Market rate must be positive"),
  guidelineRate: z.number().positive("Guideline rate must be positive"),
  constructionRate: z.number().positive("Construction rate must be positive"),

  valuationDetailsRows: z.array(valuationDetailsRowSchema),

  // Part C Extra Items
  extraPortico: z.number().nonnegative(),
  extraOrnamentalDoor: z.number().nonnegative(),
  extraSitOut: z.number().nonnegative(),
  extraOverheadTank: z.number().nonnegative(),
  extraSteelGates: z.number().nonnegative(),

  // Part D Amenities
  amenityWardrobes: z.number().nonnegative(),
  amenityGlazedTiles: z.number().nonnegative(),
  amenityExtraSinks: z.number().nonnegative(),
  amenityMarbleFlooring: z.number().nonnegative(),
  amenityInteriorDecor: z.number().nonnegative(),
  amenityArchElevation: z.number().nonnegative(),
  amenityPaneling: z.number().nonnegative(),
  amenityAluminumWorks: z.number().nonnegative(),
  amenityAluminumRails: z.number().nonnegative(),
  amenityFalseCeiling: z.number().nonnegative(),

  // Part E Miscellaneous
  miscToiletRoom: z.number().nonnegative(),
  miscLumberRoom: z.number().nonnegative(),
  miscWaterTank: z.number().nonnegative(),
  miscTreesGardening: z.number().nonnegative(),

  // Part F Services
  serviceWaterSupply: z.number().nonnegative(),
  serviceDrainage: z.number().nonnegative(),
  serviceCompoundWall: z.number().nonnegative(),
  serviceCbDeposits: z.number().nonnegative(),
  servicePavement: z.number().nonnegative(),

  // Place, Valuer & Bank Signatures
  valuationCalculationsText: z.string(),
  valuerName: z.string().min(1, "Valuer name is required"),
  valuerRegNo: z.string(),
  valuerAddress: z.string(),
  valuerPlace: z.string(),
  bankManagerName: z.string(),
  bankOfficerName: z.string(),
  bankVerificationDate: z.string(),

  // 11 Valuer Comments
  commentsValuer: z.array(z.string()).length(11),

  // Step 8: Uploads (Base64)
  photoFront: z.string(),
  photoInterior: z.string(),
  gmapsScreenshot: z.string(),
  circleRateDoc: z.string(),
  layoutPlan: z.string(),
  otherDoc: z.string(),
});

export type ValuationFormValues = z.infer<typeof valuationFormSchema>;

export const defaultValuationValues: ValuationFormValues = {
  bankName: "Punjab & Sind Bank",
  branchName: "Lehra Gaga Branch, Sangrur",
  purposeOfValuation: "Bank Purpose",
  inspectionDate: "2026-06-10",
  valuationDate: "2026-06-11",
  perusalDocuments: "1) Sale Deed No. 1024 dated 14/05/2013\n2) Approved Site Layout Plan by Municipal Council\n3) Circle Rate List issued by Collector",
  
  owners: [
    {
      ownerName: "Harpreet Singh",
      fatherHusbandName: "S. Gurdev Singh",
      mobileNumber: "9876543210",
      ownershipShare: "100% (Individual Owner)",
      address: "Ward No. 4, near Railway Station, Lehra Gaga, Sangrur, Punjab",
    },
  ],

  propertyType: "Residential",
  ownershipType: "Freehold",
  mortgageStatus: "Proposed to be mortgaged with Punjab & Sind Bank",
  plotNumber: "Plot No. 35",
  surveyNumber: "Khata No. 450/41, Khasra No. 1245",
  doorNumber: "MC Door No. 125-A",
  village: "Lehra Gaga",
  taluka: "Lehra",
  district: "Sangrur",
  state: "Punjab",
  postalAddress: "Plot No. 35, Khasra No. 1245, Ward No. 4, Lehra Gaga, Punjab - 148031",
  areaClassification: "Middle Class Area",
  areaType: "Semi Urban",
  municipalityType: "Municipal Council Lehra Gaga",
  propertyDescription: "Residential plot with self-occupied double story brick masonry structure built thereon.",
  govtEnactments: "No, covered under Punjab Municipal laws, no land ceiling dispute, not under scheduled/agency/cantonment area.",
  agriculturalConversion: "N.A. Property is within municipal limits and classified as residential house site.",

  boundaryNorthDeed: "Plot No. 36 (12 Ft Street)",
  boundaryNorthDeed2: "Plot No. 36",
  boundaryNorthSite: "Plot No. 36 (12 Ft Wide Street)",
  boundarySouthDeed: "Plot No. 34 (Owner Harpreet Singh)",
  boundarySouthDeed2: "Plot No. 34",
  boundarySouthSite: "Plot No. 34 (Built-up House)",
  boundaryEastDeed: "Plot No. 20 (Self)",
  boundaryEastDeed2: "Plot No. 20",
  boundaryEastSite: "Plot No. 20 (Built-up House)",
  boundaryWestDeed: "30 Ft Main Bazar Road",
  boundaryWestDeed2: "30 Ft Bazar Road",
  boundaryWestSite: "30 Ft Wide Bazar Road",

  dimensionNorthDeed: "45' 0\"",
  dimensionNorthDeed2: "45' 0\"",
  dimensionNorthSite: "45' 0\"",
  dimensionSouthDeed: "45' 0\"",
  dimensionSouthDeed2: "45' 0\"",
  dimensionSouthSite: "45' 0\"",
  dimensionEastDeed: "60' 0\"",
  dimensionEastDeed2: "60' 0\"",
  dimensionEastSite: "60' 0\"",
  dimensionWestDeed: "60' 0\"",
  dimensionWestDeed2: "60' 0\"",
  dimensionWestSite: "60' 0\"",

  plotArea: 300, // 300 Sq Yards
  coveredArea: 2400, // 2400 Sq Ft
  numberOfFloors: 2,
  latitude: "29.9984",
  longitude: "75.7951",
  gmapsUrl: "https://www.google.com/maps/place/29%C2%B059'54.2%22N+75%C2%B047'42.4%22E/@29.9984,75.7951,17z/",
  extentSite: "300 Sq. Yards",
  extentValuation: "300 Sq. Yards (least of Deed boundaries & Actual Site extent)",
  occupancyDetails: "Self-occupied by owner S. Harpreet Singh. No tenant. Rent Received: Nil.",

  // 20 site characteristics
  charLocality: "Residential area with mixed commercial activity nearby",
  charDevelopment: "Fully developed residential colony",
  charFlooding: "Safe, no history of water logging/flooding",
  charCivicAmenities: "Schools, hospital, bus stop, bank, market within 1 km",
  charLandLevel: "Even level with main bazar road, plain terrain",
  charLandShape: "Regular / Rectangular shape plot",
  charTypeUse: "Residential purposes",
  charUsageRestriction: "No restrictions, suitable for double story residential building",
  charTownPlanning: "Within Municipal Council approved zone",
  charCornerPlot: "Intermittent plot",
  charRoadFacilities: "Bituminous municipal road, streetlights available",
  charRoadType: "Bituminous (Tar) road in good condition",
  charRoadWidth: "More than 20 ft. (30 ft Bazar road)",
  charLandLocked: "No, open frontage to main 30 ft bazar road",
  charWaterPotential: "Good, water table at 80 ft. Municipal pipe connected",
  charSewerage: "Underground municipal sewerage system connected",
  charPowerSupply: "PSPCL three-phase electric line connected",
  charAdvantages: "Frontage on 30 ft wide bazar road, high resale value locality",
  charDisadvantages: "Minor crowd and noise from adjacent main bazar road",
  charSpecialRemarks: "The property has a clear, unencumbered marketable title with no threat of road widening or government acquisition.",

  // Building spec floor wise
  buildingType: "Residential Building",
  constructionType: "RCC Framed / Brick Masonry",
  yearOfConstruction: "2018",
  plinthArea: "Ground Floor: 1200 Sq Ft, First Floor: 1200 Sq Ft",
  conditionExterior: "Good",
  conditionInterior: "Good",
  layoutApprovalDateValidity: "Approved plan dated 12/04/2018, valid indefinitely",
  layoutApprovalAuthority: "Municipal Council Lehra Gaga",
  layoutApprovalGenuineness: "Verified from original record, found genuine",
  layoutApprovalComments: "All construction conforms to the sanctioned municipal plan.",

  specFoundationGround: "RCC Column footings and brick load bearing foundations",
  specFoundationOther: "RCC columns and beams continued upwards",
  specBasementGround: "None",
  specBasementOther: "None",
  specSuperstructureGround: "First class burnt clay brick masonry with 1:4 cement sand mortar",
  specSuperstructureOther: "First class burnt clay brick masonry with 1:4 cement sand mortar",
  specJoineryGround: "Salwood door frames with polished teak wood shutters, glazed windows",
  specJoineryOther: "Salwood door frames with flush doors, aluminum window glazed fittings",
  specRccGround: "RCC beams and slab of design mix M20",
  specRccOther: "RCC beams and slab of design mix M20",
  specPlasteringGround: "12mm thick cement sand plaster with smooth neeru finish",
  specPlasteringOther: "12mm thick cement sand plaster with smooth finish",
  specFlooringGround: "Vitrified tiles in rooms, marble tiles in lobby, glazed tiles in toilet",
  specFlooringOther: "Vitrified tiles flooring, ceramic tiles in washrooms",
  specSpecialFinishGround: "POP cornices, wooden paneling in drawing room, steel window grills",
  specSpecialFinishOther: "POP border, steel window safety grills",
  specRoofingGround: "Flat concrete slab with cement concrete waterproofing course",
  specRoofingOther: "Flat concrete slab with standard weathering course",

  // compound wall
  compoundHeight: "5' 6\" above road level",
  compoundLength: "180 Rft total length",
  compoundType: "First class brick masonry with plastering and safety iron main gate",

  // electrical
  electricalWiring: "Concealed PVC conduit wiring with multi-strand copper wires",
  electricalFitting: "Superior class modular switches and sockets (Havells/Anchor)",
  electricalLightPoints: "Ground: 18 points, First: 15 points",
  electricalFanPoints: "Ground: 6 points, First: 5 points",
  electricalPlugs: "Ground: 8 plugs, First: 8 plugs",
  electricalOther: "AC sockets: 3 Nos, Distribution DB with MCBs",

  // plumbing
  plumbingWaterClosets: "2 English type, 1 Indian type",
  plumbingWashBasins: "3 porcelain wash basins with CP fittings",
  plumbingUrinals: "1 No. urinal pot in ground floor lobby toilet",
  plumbingBathTubs: "None",
  plumbingWaterMeter: "1 Municipal connection water meter, CP taps and fixtures",
  plumbingOther: "Internal CPVC hot and cold water pipes, overhead water tank 1000L",

  // Step 7: Valuation Math & Tables
  marketRate: 15000, // Rs. 15,000 per Sq Yard
  guidelineRate: 12000, // Rs. 12,000 per Sq Yard
  constructionRate: 1600, // Rs. 1,600 per Sq Ft

  valuationDetailsRows: [
    {
      particularOfItem: "Ground Floor Structure",
      plinthArea: 1200,
      remainingAge: 50,
      depreciationPct: 8,
      replacementRate: 1600,
    },
    {
      particularOfItem: "First Floor Structure",
      plinthArea: 1200,
      remainingAge: 50,
      depreciationPct: 8,
      replacementRate: 1500,
    },
  ],

  extraPortico: 25000,
  extraOrnamentalDoor: 15000,
  extraSitOut: 18000,
  extraOverheadTank: 12000,
  extraSteelGates: 20000,

  amenityWardrobes: 45000,
  amenityGlazedTiles: 22000,
  amenityExtraSinks: 8000,
  amenityMarbleFlooring: 35000,
  amenityInteriorDecor: 50000,
  amenityArchElevation: 30000,
  amenityPaneling: 15000,
  amenityAluminumWorks: 12000,
  amenityAluminumRails: 10000,
  amenityFalseCeiling: 25000,

  miscToiletRoom: 15000,
  miscLumberRoom: 12000,
  miscWaterTank: 10000,
  miscTreesGardening: 5000,

  serviceWaterSupply: 25000,
  serviceDrainage: 20000,
  serviceCompoundWall: 35000,
  serviceCbDeposits: 8000,
  servicePavement: 12000,

  valuationCalculationsText: "Valuation has been assessed using standard Market comparison method for land and replacement cost less depreciation method for the building structure. The property sits in a prime residential-cum-commercial sector in Lehra Gaga. Prevailing transactions in adjacent plots show rates between Rs.14,500 and Rs.16,000 per Sq Yard. Guideline rate is Rs.12,000 per Sq Yard. We adopt Rs.15,000 per Sq Yard. Building replacement rate is adopted at Rs.1600/sqft for ground and Rs.1500/sqft for first floor structure in accordance with CPWD index and local builder enquiries. Depreciation of 8% is applied for the building based on standard age-based linear scale.",
  
  valuerName: "Bhagwan Dass",
  valuerRegNo: "CAT-I/45-A/Sangrur/PSB",
  valuerAddress: "Opp. Punjab & Sind Bank Branch, Main Bazar Road, Lehra Gaga, Sangrur, Punjab",
  valuerPlace: "Lehra Gaga",
  bankManagerName: "Er. G.S. Gill",
  bankOfficerName: "Sh. A.K. Sharma",
  bankVerificationDate: "2026-06-11",

  commentsValuer: [
    "Residential two-story building located at Khasra No. 1245, Plot No. 35, Ward No. 4, Lehra Gaga, Sangrur, Punjab.",
    "Property valuation is requested for securing credit facilities (LAP) proposed to be sanctioned by Punjab & Sind Bank.",
    "Bhagwan Dass, Approved Valuer, CAT-I/45-A/Sangrur/PSB. No other experts were involved.",
    "The valuer has no direct or indirect interest, financial or otherwise, in the property being valued.",
    "Appointment dated 08/06/2026, Valuation date 11/06/2026, Report date 11/06/2026.",
    "Physical inspection of boundaries, dimensions, plinth areas, and specifications on 10/06/2026.",
    "Relying on Sale Deed No. 1024 (14/05/2013), Circle Rate records, municipal plans, and local market transaction details.",
    "Market Comparison Method for land valuation and Replacement Cost Less Depreciation Method for building structure.",
    "Exclusive use for Punjab & Sind Bank credit assessment. Cannot be used for litigation, public claims, or tax disputes.",
    "Location on 30 ft wide bazar road, municipal sewer connection, quality construction, market demand, age of building.",
    "Valuation report is subject to verification of land registry record authenticity. Title validity is assumed clear."
  ],

  photoFront: "",
  photoInterior: "",
  gmapsScreenshot: "",
  circleRateDoc: "",
  layoutPlan: "",
  otherDoc: "",
  pincode: "148031",
};

export const emptyValuationValues: ValuationFormValues = {
  bankName: "Punjab & Sind Bank",
  branchName: "",
  purposeOfValuation: "",
  inspectionDate: "",
  valuationDate: "",
  perusalDocuments: "",
  owners: [
    {
      ownerName: "",
      fatherHusbandName: "",
      mobileNumber: "",
      ownershipShare: "",
      address: "",
    },
  ],
  propertyType: "Residential",
  ownershipType: "Freehold",
  mortgageStatus: "",
  plotNumber: "",
  surveyNumber: "",
  doorNumber: "",
  village: "",
  taluka: "",
  district: "",
  state: "Punjab",
  postalAddress: "",
  pincode: "",
  areaClassification: "",
  areaType: "",
  municipalityType: "",
  propertyDescription: "",
  govtEnactments: "",
  agriculturalConversion: "",
  boundaryNorthDeed: "",
  boundaryNorthDeed2: "",
  boundaryNorthSite: "",
  boundarySouthDeed: "",
  boundarySouthDeed2: "",
  boundarySouthSite: "",
  boundaryEastDeed: "",
  boundaryEastDeed2: "",
  boundaryEastSite: "",
  boundaryWestDeed: "",
  boundaryWestDeed2: "",
  boundaryWestSite: "",
  dimensionNorthDeed: "",
  dimensionNorthDeed2: "",
  dimensionNorthSite: "",
  dimensionSouthDeed: "",
  dimensionSouthDeed2: "",
  dimensionSouthSite: "",
  dimensionEastDeed: "",
  dimensionEastDeed2: "",
  dimensionEastSite: "",
  dimensionWestDeed: "",
  dimensionWestDeed2: "",
  dimensionWestSite: "",
  plotArea: 0,
  coveredArea: 0,
  numberOfFloors: 1,
  latitude: "",
  longitude: "",
  gmapsUrl: "",
  extentSite: "",
  extentValuation: "",
  occupancyDetails: "",
  charLocality: "",
  charDevelopment: "",
  charFlooding: "",
  charCivicAmenities: "",
  charLandLevel: "",
  charLandShape: "",
  charTypeUse: "",
  charUsageRestriction: "",
  charTownPlanning: "",
  charCornerPlot: "",
  charRoadFacilities: "",
  charRoadType: "",
  charRoadWidth: "",
  charLandLocked: "",
  charWaterPotential: "",
  charSewerage: "",
  charPowerSupply: "",
  charAdvantages: "",
  charDisadvantages: "",
  charSpecialRemarks: "",
  buildingType: "Residential Building",
  constructionType: "RCC Framed",
  yearOfConstruction: "",
  plinthArea: "",
  conditionExterior: "",
  conditionInterior: "",
  layoutApprovalDateValidity: "",
  layoutApprovalAuthority: "",
  layoutApprovalGenuineness: "",
  layoutApprovalComments: "",
  specFoundationGround: "",
  specFoundationOther: "",
  specBasementGround: "",
  specBasementOther: "",
  specSuperstructureGround: "",
  specSuperstructureOther: "",
  specJoineryGround: "",
  specJoineryOther: "",
  specRccGround: "",
  specRccOther: "",
  specPlasteringGround: "",
  specPlasteringOther: "",
  specFlooringGround: "",
  specFlooringOther: "",
  specSpecialFinishGround: "",
  specSpecialFinishOther: "",
  specRoofingGround: "",
  specRoofingOther: "",
  compoundHeight: "",
  compoundLength: "",
  compoundType: "",
  electricalWiring: "",
  electricalFitting: "",
  electricalLightPoints: "",
  electricalFanPoints: "",
  electricalPlugs: "",
  electricalOther: "",
  plumbingWaterClosets: "",
  plumbingWashBasins: "",
  plumbingUrinals: "",
  plumbingBathTubs: "",
  plumbingWaterMeter: "",
  plumbingOther: "",
  marketRate: 0,
  guidelineRate: 0,
  constructionRate: 0,
  valuationDetailsRows: [
    {
      particularOfItem: "Ground Floor Structure",
      plinthArea: 0,
      remainingAge: 0,
      depreciationPct: 0,
      replacementRate: 0,
    },
  ],
  extraPortico: 0,
  extraOrnamentalDoor: 0,
  extraSitOut: 0,
  extraOverheadTank: 0,
  extraSteelGates: 0,
  amenityWardrobes: 0,
  amenityGlazedTiles: 0,
  amenityExtraSinks: 0,
  amenityMarbleFlooring: 0,
  amenityInteriorDecor: 0,
  amenityArchElevation: 0,
  amenityPaneling: 0,
  amenityAluminumWorks: 0,
  amenityAluminumRails: 0,
  amenityFalseCeiling: 0,
  miscToiletRoom: 0,
  miscLumberRoom: 0,
  miscWaterTank: 0,
  miscTreesGardening: 0,
  serviceWaterSupply: 0,
  serviceDrainage: 0,
  serviceCompoundWall: 0,
  serviceCbDeposits: 0,
  servicePavement: 0,
  valuationCalculationsText: "",
  valuerName: "Bhagwan Dass",
  valuerRegNo: "CAT-I/45-A/Sangrur/PSB",
  valuerAddress: "Opp. Punjab & Sind Bank Branch, Main Bazar Road, Lehra Gaga, Sangrur, Punjab",
  valuerPlace: "Lehra Gaga",
  bankManagerName: "",
  bankOfficerName: "",
  bankVerificationDate: "",
  commentsValuer: ["", "", "", "", "", "", "", "", "", "", ""],
  photoFront: "",
  photoInterior: "",
  gmapsScreenshot: "",
  circleRateDoc: "",
  layoutPlan: "",
  otherDoc: "",
};
